app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='app-home'),
    path('about/', views.about, name='app-about'),

    path('applicant/list/',views.applicant_list,name='applicant_list'),
    path('applicant/new/', views.applicant_form,name='applicant_insert'),
    path('applicant/<int:id>/update/', views.applicant_form,name='applicant_update'),
    path('applicant/<int:id>/delete/',views.applicant_delete,name='applicant_delete'),

    path('organization/list/',views.organization_list,name='organization_list'),
    path('organization/new/', views.organization_form,name='organization_insert'),
    path('organization/<int:id>/update/', views.organization_form,name='organization_update'),
    path('organization/<int:id>/delete/',views.organization_delete,name='organization_delete'),

    path('application/list/',views.application_list,name='application_list'),
    path('application/new/', views.application_form,name='application_insert'),
    path('application/<int:id>/update/', views.application_form,name='application_update'),
    path('application/<int:id>/delete/',views.application_delete,name='application_delete'),
]

managing_transactions/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.DOCLIB_URL, document_root=settings.DOCLIB_ROOT)

app/models.py
import datetime
from django.db import models
from django.utils.translation import gettext as _
# from django.urls import reverse
# from django.utils import timezone
from django.contrib.auth.models import User

class Applicant(models.Model):

    gender_list = (
        ('male', 'Male'),
        ('female', 'Female'),
    )

    qualification_list = (
        ('secondary_school', 'Secondary School'),
        ('diploma', 'Diploma'),
        ('bsc', 'BSc'),
        ('high_diploma', 'High Diploma'),
        ('master', 'Master'),
        ('phd', 'PhD'),
    )

    nationality_list = (
        ('none', 'Select your nationality'),
        ('bahraini', 'Bahraini'),
        ('non_bahraini', 'None Bahraini')
    )

    cpr = models.CharField(_("CPR No"), max_length=9)
    cpr_expiry_date = models.DateField(_("CPR Expire Date"), auto_now=False, auto_now_add=False)
    passport_expiry_date = models.DateField(_("Passport Expire Date"), auto_now=False, auto_now_add=False)
    fullname = models.CharField(_("Full Name"), max_length=100)
    nationality =  models.CharField(_("Nationality"), max_length=50, choices=nationality_list, default='none')
    gender = models.CharField(_("Gender"), max_length=10, choices=gender_list)
    qualification = models.CharField(_("Qualification"), max_length=50, choices=qualification_list)
    occupcation = models.CharField(_("Occupation"), max_length=50)
    has_application = models.BooleanField(_("Has Applicatino on process"), default=False)

    # Address fields
    flat_no = models.IntegerField(_("Flat No"), default=0)
    building_no = models.IntegerField(_("Building No"), default=0)
    road_no = models.IntegerField(_("Road No"), default=0)
    area = models.CharField(_("Area"), max_length=50, blank=True)
    contact1 = models.CharField(_("Phone"), max_length=50, blank=True)
    contact2 = models.CharField(_("Mobile"), max_length=50, blank=True)
    email = models.EmailField(_("Email"), max_length=254, blank=True)
    user_id = models.ForeignKey(User, verbose_name=_(""), on_delete=models.CASCADE)

    # Applicant Uploaded Doc fields
    cpr_doc = models.FileField(_("CPR Doc"), upload_to='doc_library', max_length=100)
    passport_doc = models.FileField(_("Passport Doc"), upload_to='doc_library', max_length=100)
    behavior_cert_doc = models.FileField(_("Behavior Certificate Doc"), upload_to='doc_library', max_length=100)
    bank_statement_doc = models.FileField(_("Bank Statement Doc"), upload_to='doc_library', max_length=100)
    is_10000_exist = models.BooleanField(_("Is 10000 BD exist in Applicant Bank Statement"), default=False)

    def __str__(self):
        return self.cpr + ' --- ' + self.fullname

class Organization(models.Model):

    cr = models.CharField(_("CR No"), max_length=50, blank=True)
    cr_reg_date = models.DateField(_("Registration Date"), auto_now=False, auto_now_add=False)
    full_en_name = models.CharField(_("Commercial Eng Name"), max_length=250, blank=True)
    license_no = models.CharField(_("License No"), max_length=50, blank=True)
    flat_no = models.IntegerField(_("Flat No"), default=0)
    building_no = models.IntegerField(_("Building No"), default=0)
    road_no = models.IntegerField(_("Road No"), default=0)
    area = models.CharField(_("Area"), max_length=50, blank=True)
    contact1 = models.CharField(_("Phone"), max_length=50, blank=True)
    contact2 = models.CharField(_("Fax"), max_length=50, blank=True)
    email = models.EmailField(_("Email"), max_length=254, blank=True)

    #Owner of compnay
    applicant_id = models.ForeignKey(Applicant, verbose_name=_(""), on_delete=models.CASCADE, blank=True)

    #User who creates this record in the system
    user_id = models.ForeignKey(User, verbose_name=_(""), on_delete=models.CASCADE, blank=True)

    # cr_doc = models.FileField(_("CR Doc"), upload_to='doc_library', max_length=100)
    # bank_statement_doc = models.FileField(_("Bank Statement Doc"), upload_to='doc_library', max_length=100)
    # lmra_agreement = models.FileField(_("LMRA Agreement"), upload_to='doc_library', max_length=100)

    def __str__(self):
        return self.full_en_name

class Application(models.Model):

    activity_type_list = (
        ('demostic', 'Demostic Labour Employment'),
        ('foreign', 'Foreign Labour Employement'),
        ('local', 'Bahraini Labour Employment')
    )

    financial_guarantee_list = (
        ('manager_cheque', 'Manager Cheque'),
        ('bank_guarantee', 'Bank Guarantee')
    )

    intial_approval_list = (
        ('approve', 'Approve'),
        ('reject', 'Reject')
    )

    app_type_list = (
        ('initial','Initial Approval'),
        ('final','Final Approval'),
        ('renew','Renewal License'),
        ('cancel','Cancel License')
    )

    app_no = models.CharField(_("Application No"), max_length=50, default='Draft Application')
    app_date = models.DateField(_("Application Date"), default=datetime.date.today)
    app_type = models.CharField(_("Application Type"), max_length=50, choices=app_type_list)
    app_status_index = models.IntegerField(_("Status No"), default=0)
    app_current_status = models.CharField(_("Status"), max_length=50, default='Draft')
    app_next_status = models.CharField(_("Status"), max_length=50, default='Draft')
    activty_type = models.CharField(_("Activity Type"), max_length=50, choices=activity_type_list)
    staff_comments = models.TextField(_("Comments"), blank=True)
    manager_comments = models.TextField(_("Manager Comments"), blank=True)
    approval = models.CharField(_("Manager Decision"), max_length=50, choices=intial_approval_list, blank=True)

    financial_guarantee = models.CharField(_("Financial Guarantee"), max_length=50, choices=financial_guarantee_list, blank=True)
    financial_guarantee_expiry_date = models.DateField(_("Financial Guarantee Expiry Date"), null=True, blank=True)

    # start -- org details
    # will be updated by Layla
    cr = models.CharField(_("CR No"), max_length=50, blank=True)
    cr_reg_date = models.DateField(_("Registration Date"), null=True, blank=True)
    full_en_name = models.CharField(_("Commercial Eng Name"), max_length=250, blank=True)
    license_no = models.CharField(_("License No"), max_length=50, blank=True)
    license_expiry_date = models.DateField(_("License Expiry Date"), null=True, blank=True)
    flat_no = models.IntegerField(_("Flat No"), default=0)
    building_no = models.IntegerField(_("Building No"), default=0)
    road_no = models.IntegerField(_("Road No"), default=0)
    area = models.CharField(_("Area"), max_length=50, blank=True)
    contact1 = models.CharField(_("Phone"), max_length=50, blank=True)
    contact2 = models.CharField(_("Fax"), max_length=50, blank=True)
    email = models.EmailField(_("Email"), max_length=254, blank=True)
    # end -- org details

    # start -- female accomodation
    fh_flat_no = models.IntegerField(_("Flat No"), default=0)
    fh_building_no = models.IntegerField(_("Building No"), default=0)
    fh_road_no = models.IntegerField(_("Road No"), default=0)
    fh_area = models.CharField(_("Area"), max_length=50, blank=True)
    fh_contact1 = models.CharField(_("Phone"), max_length=50, blank=True)
    fh_contact2 = models.CharField(_("Fax"), max_length=50, blank=True)

    qsreq = models.IntegerField(_("Uploaded Documents"), default=0)
    qnreq = models.IntegerField(_("Org Required Documents"), default=1)
    dreq = models.FloatField(_("Adequacy of Requirements Level"), default=0)

    qsrec = models.IntegerField(_("Satisfying Recommendations"), default=0)
    qnrec = models.IntegerField(_("All Recommendations"), default=1)
    drec = models.FloatField(_("Adequacy of Recommendations Level"), default=0)

    #Attachments
    cr_doc = models.FileField(_("CR Doc"), upload_to='doc_library', max_length=100, null=True, blank=True)
    bank_statement_doc = models.FileField(_("Bank Statement Doc"), upload_to='doc_library', max_length=100, null=True, blank=True)
    lmra_agreement = models.FileField(_("LMRA Agreement"), upload_to='doc_library', max_length=100, null=True, blank=True)
    cert1_doc = models.FileField(_("MOIS Cert"), upload_to='doc_library', max_length=100, null=True, blank=True)
    cert2_doc = models.FileField(_("MOH Cert"), upload_to='doc_library', max_length=100, null=True, blank=True)
    cert3_doc = models.FileField(_("MOL Cert"), upload_to='doc_library', max_length=100, null=True, blank=True)
    cr_rent_doc = models.FileField(_("CR Rental Agreement Doc"), upload_to='doc_library', max_length=100, null=True, blank=True)
    fh_rent_doc = models.FileField(_("Temp FH Rental Agreement Doc"), upload_to='doc_library', max_length=100, null=True, blank=True)
    cr_ewa_bill_doc = models.FileField(_("CR EWA Bill Doc"), upload_to='doc_library', max_length=100, null=True, blank=True)
    fh_ewa_bill_doc = models.FileField(_("Temp FH EWA Bill Doc"), upload_to='doc_library', max_length=100, null=True, blank=True)
    employment_office_receipt = models.FileField(_("Employment Office Receipt"), upload_to='doc_library', max_length=100, null=True, blank=True)


    applicant_id = models.ForeignKey(Applicant, verbose_name=_(""), on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, verbose_name=_(""), on_delete=models.CASCADE)


    def __str__(self):
        return self.app_no

app/templates/app/about.html
{% extends "app/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

app/templates/app/applicant_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<h1 class="display-4">Applicant Form</h1>
<p class="lead font-italic">Any Text can be placed here</p>
<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    {{form.fullname|as_crispy_field}}
    {{form.cpr|as_crispy_field}}
    {{form.cpr_expiry_date|as_crispy_field}}
    <div class="row">
        <div class="form-group col-md-6 mb-0">
            {{ form.gender|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.nationality|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.qualification|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.occupcation|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
            {{ form.flat_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
            {{ form.building_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
            {{ form.road_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.area|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.contact1|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.contact2|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.email|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.passport_expiry_date|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
           {{ form.user_id|as_crispy_field }}
        </div>
        <div class="form-group col-md-12 mb-0">
           {{ form.cpr_doc|as_crispy_field }}
        </div>
        <div class="form-group col-md-12 mb-0">
           {{ form.passport_doc|as_crispy_field }}
        </div>
        <div class="form-group col-md-12 mb-0">
           {{ form.behavior_cert_doc|as_crispy_field }}
        </div>
        <div class="form-group col-md-12 mb-0">
           {{ form.bank_statement_doc|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i>
                Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'applicant_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
    </div>

</form>
{% endblock content %}

app/templates/app/applicant_list.html
{% extends "app/base.html" %}


{% block content %}
<h1 class="display-4">Applicant List</h1>
<p class="lead font-italic">Any Text can be placed here</p>
<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Full Name</td>
            <td>Mobile</td>
            <td>CPR</td>
            <td>CPR Expiry Date</td>
            <td>
                {% if user.is_authenticated %}
                    <a href="{% url 'applicant_insert' %}" class="btn btn-outline-success">
                        <i class="fas fa-plus"></i> Add New
                    </a>
                {% endif %}
            </td>
        </tr>
    </thead>
    <tbody>
        {% for applicant in applicant_list %}
            <tr>
                <td>{{applicant.fullname}}</td>
                <td>{{applicant.contact2}}</td>
                <td>{{applicant.cpr}}</td>
                <td>{{applicant.cpr_expiry_date}}</td>
                <td>
                {% if user.is_authenticated %}
                    <a href="{% url 'applicant_update' applicant.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'applicant_delete' applicant.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>
                    </form>
                {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

app/templates/app/application_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}
{% load user_tags %}
{% block content %}
<h1 class="display-4">Application Form</h1>
<p class="lead font-italic">Any Text can be placed here</p>
<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    <div class="row">
        <div class="form-group col-md-6 mb-0">
            {{ form.app_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.app_date|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.app_type|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.app_current_status|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.app_next_status|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.app_status_index|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.activty_type|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.email|as_crispy_field }}
        </div>

        {% if form.instance.app_type != 'initial' %}
        <div class="form-group col-md-12">
            <h3>Company Details</h3>
        </div>
        {% endif %}
        <div class="form-group col-md-6 mb-0">
            {{ form.cr|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.cr_reg_date|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.full_en_name|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.license_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.license_expiry_date|as_crispy_field }}
        </div>

        {% if form.instance.app_type != 'initial' %}
        <div class="form-group col-md-12">
            <h3>Address Details</h3>
        </div>
        {% endif %}
        <div class="form-group col-md-6 mb-0">
            {{ form.flat_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.building_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.road_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.area|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.contact1|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.contact2|as_crispy_field }}
        </div>

        {% if form.instance.app_type != 'initial' %}
        <div class="form-group col-md-12">
            <h3>Female Accommodation Address Details</h3>
        </div>
        {% endif %}
        <div class="form-group col-md-6 mb-0">
            {{ form.fh_flat_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.fh_building_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.fh_road_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.fh_area|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.fh_contact1|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.fh_contact2|as_crispy_field }}
        </div>




        <div class="form-group col-md-6 mb-0">
            {{ form.financial_guarantee|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.financial_guarantee_expiry_date|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0"></div>
        {% if user.is_authenticated %}
            {% if user.is_staff %}
        <div class="form-group col-md-12 mb-0">
            {{ form.staff_comments|as_crispy_field }}
        </div>
            {% endif %}
            {% if request.user|has_group:"managers" %}
        <div class="form-group col-md-12 mb-0">
            {{ form.manager_comments|as_crispy_field }}
        </div>
        <div class="form-group col-md-12 mb-0">
            {{ form.approval|as_crispy_field }}
        </div>
            {% endif %}

            {% if request.user|has_group:"level 1" %}
        <div class="form-group col-md-4 mb-0">
            {{ form.qsreq|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
            {{ form.qnreq|as_crispy_field }}
        </div>

        <div class="form-group col-md-4 mb-0">
            {{ form.dreq|as_crispy_field }}
        </div>
            {% endif %}
            {% if request.user|has_group:"level 2" %}
         <div class="form-group col-md-4 mb-0">
            {{ form.qsrec|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
            {{ form.qnrec|as_crispy_field }}
        </div>
        <div class="form-group col-md-4 mb-0">
            {{ form.drec|as_crispy_field }}
        </div>
            {% endif %}
        {% endif %}
        <div class="form-group col-md-6 mb-0">
            {{ form.applicant_id|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.user_id|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            {% if user.is_authenticated %}
                {% if user.is_staff %}
                    {% if form.instance.app_type == 'initial' %}
                        {% if form.instance.app_status_index < 7 %}
                            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i> {{form.instance.app_next_status}}</button>
                        {% endif %}
                    {% elif form.instance.app_type == 'final'  %}
                        {% if form.instance.app_status_index < 8 %}
                            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i> {{form.instance.app_next_status}}</button>
                        {% endif %}
                    {% elif form.instance.app_type == 'renew'  %}
                        {% if form.instance.app_status_index < 8 %}
                            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i> {{form.instance.app_next_status}}</button>
                        {% endif %}
                    {% endif %}
                {% else %}

                        {% if form.instance.app_current_status == 'Draft' %}
                            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i> Submit</button>
                        {% endif %}

                {% endif %}
            {% endif %}
        </div>
        <div class="col-md-4">
            <a href="{% url 'application_list' %}" class="btn btn-secondary btn-block btn-lg"> <i class="fas fa-stream"></i> Back to list </a>
        </div>
    </div>
</form>
{% endblock content %}

app/templates/app/application_list.html
{% extends "app/base.html" %}


{% block content %}
<h1 class="display-4">Application List</h1>
<p class="lead font-italic">Any Text can be placed here</p>
<table class="table table-borderless">
    <thead class="border-bottom font-weight-bold">
        <tr>
            <td>Name</td>
            <td>Date</td>
            <td>Type</td>
            <td>Status</td>
            <td>Activity Type</td>
            <td>Applicant</td>
            <td>Created By</td>
            <td>
                {% if user.is_authenticated %}
                    <a href="{% url 'application_insert' %}" class="btn btn-outline-success">
                        <i class="fas fa-plus"></i> Add New
                    </a>
                    {% comment %} <a href="{% url 'application_insert' %}" class="btn btn-outline-success">
                        <i class="fas fa-plus"></i> Add New
                    </a> {% endcomment %}
                {% endif %}

            </td>
        </tr>
    </thead>
    <tbody>
        {% for application in application_list %}
            <tr>
                <td>{{application.app_no}}</td>
                <td>{{application.app_date}}</td>
                <td>{{application.get_app_type_display}}</td>
                <td>{{application.app_current_status}}</td>
                <td>{{application.get_activty_type_display}}</td>
                <td>{{application.applicant_id.fullname}}</td>
                <td>{{application.user_id.username}}</td>
                <td>
                {% if user.is_authenticated %}
                    <a href="{% url 'application_update' application.id %}" class="btn text-secondary px-0">
                        <i class="far fa-edit fa-lg"></i>
                    </a>
                    <form action="{% url 'application_delete' application.id %}" method="post" class="d-inline">
                        {% csrf_token %}
                        <button type="submit" class="btn">
                            <i class="far fa-trash-alt fa-lg text-danger float-right"></i>
                        </button>
                    </form>
                {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

app/templates/app/home.html
{% extends "app/base.html" %}
{% comment %} {% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %} {% endcomment %}

app/templates/app/organization_form.html
{% extends "app/base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<h1 class="display-4">Organization Form</h1>
<p class="lead font-italic">Any Text can be placed here</p>
<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    {{form.full_en_name|as_crispy_field}}
    {{form.cr|as_crispy_field}}
    {{form.cr_reg_date|as_crispy_field}}
     <div class="row">
        <div class="form-group col-md-6 mb-0">
            {{ form.flat_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.building_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.road_no|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.area|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.contact1|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.contact2|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
            {{ form.email|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
           {{ form.applicant_id|as_crispy_field }}
        </div>
        <div class="form-group col-md-6 mb-0">
           {{ form.user_id|as_crispy_field }}
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <button type="submit" class="btn btn-success btn-block btn-lg"><i class="fas fa-database"></i>
                Submit</button>
        </div>
        <div class="col-md-4">
            <a href="{% url 'organization_list' %}" class="btn btn-secondary btn-block btn-lg">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </div>
    </div>

</form>
{% endblock content %}

app/templates/app/success.html
{% extends 'app/base.html' %}

{% block content %}
  <p class="text-success">Form processed with success!</p>
{% endblock %}